after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "to-457-docker-ci" ]; then # replace branch with master
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      make build;
      make docker-push;
    fi
